language: python
python:
  - "2.7"

node_js:
  - "6.11.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - npm install -g grunt-cli
  - npm install
# command to run tests
script:
  - npm test

dist: trusty
sudo: required
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu
  - echo "//packages.infragistics.com/npm/:_authToken=\${NPM_TOKEN}" > .npmrc
